### ISSUE TITLE
publish on pypi

### ISSUE THREAD

**Issue by DetachHead** [AThePeanut4/docify#3]
this would make it easier to depend on this script as part of my project. i can make a PR for this if you want

**Comment by atoerien** [comment]
Yeah I do plan on doing that, need to first figure out how Python packaging works lol

There's also already a package on PyPI called Docify (https://pypi.org/project/Docify), which is luckily abandoned so it seems like I should be able to get the name transferred - that could potentially take a while though.

**Comment by jorenham** [comment]
This lack of a `pyproject.toml` appears to be causing the `basedpyright==1.13.0` pre-commit hook to fail:
https://github.com/DetachHead/basedpyright/issues/430

Note that this could be solved without publishing to pypi; having a `pyproject.toml` would be sufficient in this case.

**Comment by atoerien** [comment]
I've added a `pyproject.toml`, still busy figuring out the best way to package/build/etc. I will publish on PyPI once that's worked out.

I have also been able to get the project name transferred over, so that issue is resolved.

@DetachHead Just FYI I changed the method signature for `main` to make it work with the `project.scripts` key, so you'll need to change the usage in `basedpyright`, or use `run`.

**Comment by DetachHead** [comment]
> I've added a `pyproject.toml`, still busy figuring out the best way to package/build/etc. I will publish on PyPI once that's worked out.

if you want my opinion, [pdm with pyprojectx](https://pdm-project.org/en/latest/#__tabbed_2_6) has given me the least painful experience managing a python project. [publishing is quite easy especially when you use the trusted publisher feature](https://pdm-project.org/en/latest/usage/publish/). (pyprojectx isn't needed, but it makes it much easier for potential contributors to get set up for local development)

**Comment by atoerien** [comment]
All done: https://pypi.org/project/docify
