### ISSUE TITLE
BUG: Improper handling of `__init__.pyi`

### ISSUE THREAD

**Issue by ValdezFOmar** [AThePeanut4/docify#9]
I'm using [tree-sitter](https://github.com/tree-sitter/py-tree-sitter) and wanted to add docstrings to its type stubs (which are in the [`__init__.pyi`](https://github.com/tree-sitter/py-tree-sitter/blob/master/tree_sitter/__init__.pyi) file), but I got `WARNING: could not import __init__, module not found`:

```console
$ python -m venv .venv
$ activate .venv/bin/activate
$ pip install docify tree-sitter
$ mkdir typings
$ docify .venv/lib/python3.9/site-packages/tree_sitter -o typings/
WARNING: could not import __init__, module not found                                                                                
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 5133.79it/s]
```

I think the issue is here:

https://github.com/AThePeanut4/docify/blob/c428e426af89408744cb86137d9e1e4fdd2185a7/docify.py#L562-L570

Since the relative path of `.venv/lib/python3.9/site-packages/tree_sitter/__init__.pyi` to `.venv/lib/python3.9/site-packages/tree_sitter/` is `__ini__.pyi` and thus the import path is `__init__` which doesn't match with `.__init__`. And even if it matched, the module name would end up being the empty string, so and extra check would be needed for that.

The script does work if instead of `.venv/lib/python3.9/site-packages/tree_sitter` I use `.venv/lib/python3.9/site-packages/`, but that has the consequence of adding docstring to all the installed modules, which is not ideal:

```console
$ docify .venv/lib/python3.9/site-packages/ -o typings/
INFO: processing tree_sitter_python/__init__.pyi                                                                                    
INFO: processing tree_sitter/__init__.pyi   # This is the only one that I care about                                                                                        
INFO: processing setuptools/_vendor/jaraco/functools/__init__.pyi                                                                   
INFO: processing setuptools/_vendor/more_itertools/recipes.pyi                                                                      
INFO: processing setuptools/_vendor/more_itertools/more.pyi                                                                         
INFO: processing setuptools/_vendor/more_itertools/__init__.pyi                                                                     
INFO: processing pkg_resources/_vendor/jaraco/functools/__init__.pyi                                                                
INFO: processing pkg_resources/_vendor/more_itertools/recipes.pyi                                                                   
INFO: processing pkg_resources/_vendor/more_itertools/more.pyi                                                                      
INFO: processing pkg_resources/_vendor/more_itertools/__init__.pyi                                                                  
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.51it/s]
```

**Comment by ValdezFOmar** [comment]
Also, just as a recommendation, you might be interested in using the [`pathlib` module](https://docs.python.org/3/library/pathlib.html) instead of the `os.path.*` functions for manipulating paths, as it gives you better tools to avoid problems like this.

**Comment by atoerien** [comment]
This is technically intentional behaviour, because the `INPUT_DIR` argument is meant to be the import "root" that the dynamic imports are created relative to. So with a filesystem that contains `foo/bar/module.py`, `docify foo/bar` will import just `module`, `docify foo` will import `bar.module`, and `docify .` will import `foo.bar.module`. The reason it is like this is because the script was originally only meant to add docstrings to typeshed's stdlib stubs.

I think what I'll do is add a special case where if an `__init__.pyi` (or `__init__.py`) file exists directly in the input dir then it will include it in the import path, i.e. the parent folder will then be the import root.

Also yes I am aware of the `pathlib` module, never really used it before but it does seem like it would be useful. I'll do some investigation and probably switch over if the code ends up being sufficiently simpler.
